name: qr_mobile_vision_example
description: Demonstrates how to use the qr_mobile_vision plugin.

version: 1.0.0+0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: 2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  qr_mobile_vision:
    path: ../

flutter:
  uses-material-design: true